config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :check_ins
  root "check_ins#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/check_in.rb
class CheckIn < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/check_ins_controller.rb
class CheckInsController < ApplicationController
  before_action :set_check_in, only: [:show, :edit, :update, :destroy]

  # GET /check_ins
  # GET /check_ins.json
  def index
    @check_ins = CheckIn.all
  end

  # GET /check_ins/1
  # GET /check_ins/1.json
  def show
  end

  # GET /check_ins/new
  def new
    @check_in = CheckIn.new
  end

  # GET /check_ins/1/edit
  def edit
  end

  # POST /check_ins
  # POST /check_ins.json
  def create
    @check_in = CheckIn.new(check_in_params)

    respond_to do |format|
      if @check_in.save
        format.html { redirect_to @check_in, notice: 'Check in was successfully created.' }
        format.json { render :show, status: :created, location: @check_in }
      else
        format.html { render :new }
        format.json { render json: @check_in.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /check_ins/1
  # PATCH/PUT /check_ins/1.json
  def update
    respond_to do |format|
      if @check_in.update(check_in_params)
        format.html { redirect_to @check_in, notice: 'Check in was successfully updated.' }
        format.json { render :show, status: :ok, location: @check_in }
      else
        format.html { render :edit }
        format.json { render json: @check_in.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /check_ins/1
  # DELETE /check_ins/1.json
  def destroy
    @check_in.destroy
    respond_to do |format|
      format.html { redirect_to check_ins_url, notice: 'Check in was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_check_in
      @check_in = CheckIn.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def check_in_params
      params.require(:check_in).permit(:mile_run, :push_ups, :sit_ups, :weight)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/check_ins_helper.rb
module CheckInsHelper
end

app/views/check_ins/_form.html.erb
<%= form_for(check_in) do |f| %>
  <% if check_in.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(check_in.errors.count, "error") %> prohibited this check_in from being saved:</h2>

      <ul>
      <% check_in.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :mile_run %>
    <%= f.number_field :mile_run %>
  </div>

  <div class="field">
    <%= f.label :push_ups %>
    <%= f.number_field :push_ups %>
  </div>

  <div class="field">
    <%= f.label :sit_ups %>
    <%= f.number_field :sit_ups %>
  </div>

  <div class="field">
    <%= f.label :weight %>
    <%= f.number_field :weight %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/check_ins/edit.html.erb
<h1>Editing Check In</h1>

<%= render 'form', check_in: @check_in %>

<%= link_to 'Show', @check_in %> |
<%= link_to 'Back', check_ins_path %>

app/views/check_ins/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Check Ins</h1>

<table>
  <thead>
    <tr>
      <th>Mile run</th>
      <th>Push ups</th>
      <th>Sit ups</th>
      <th>Weight</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @check_ins.each do |check_in| %>
      <tr>
        <td><%= check_in.mile_run %></td>
        <td><%= check_in.push_ups %></td>
        <td><%= check_in.sit_ups %></td>
        <td><%= check_in.weight %></td>
        <td><%= link_to 'Show', check_in %></td>
        <td><%= link_to 'Edit', edit_check_in_path(check_in) %></td>
        <td><%= link_to 'Destroy', check_in, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Check In', new_check_in_path %>

app/views/check_ins/new.html.erb
<h1>New Check In</h1>

<%= render 'form', check_in: @check_in %>

<%= link_to 'Back', check_ins_path %>

app/views/check_ins/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Mile run:</strong>
  <%= @check_in.mile_run %>
</p>

<p>
  <strong>Push ups:</strong>
  <%= @check_in.push_ups %>
</p>

<p>
  <strong>Sit ups:</strong>
  <%= @check_in.sit_ups %>
</p>

<p>
  <strong>Weight:</strong>
  <%= @check_in.weight %>
</p>

<%= link_to 'Edit', edit_check_in_path(@check_in) %> |
<%= link_to 'Back', check_ins_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tracker</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>